<a href="https://colab.research.google.com/github/HemanthVinjarapu/fml-lab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!python --version

Python 3.10.12


## Numpy

In [1]:
import numpy as np

###Arrays

In [15]:
a = np.array([1, 2, 3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [14]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
b[0]

array([1., 1.])

In [16]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [17]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [18]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [19]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [20]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [21]:
e = np.random.random((2,2))
print(e)

[[0.35678044 0.75091931]
 [0.73854876 0.71350783]]


###Array indexing

In [22]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [26]:
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [24]:

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [29]:

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [30]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a.shape)
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

(3, 2)
[1 4 5]
[1 4 5]


In [31]:

print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [32]:

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:

b = np.array([0, 2, 0, 1])
print(b)
print(a[:, b])

[0 2 0 1]
[[ 1  3  1  2]
 [ 4  6  4  5]
 [ 7  9  7  8]
 [10 12 10 11]]


In [35]:

a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [36]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [37]:

print(a[bool_idx])
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


###Datatypes

In [38]:
x = np.array([1, 2])
y = np.array([1.0, 2.0])
z = np.array([1, 2], dtype=np.int64)

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


###Array math

In [39]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)


print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [40]:

print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [41]:

print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [42]:

print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [44]:

print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [62]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
print(v.shape, w.shape)
print(v.dot(w))
print(np.dot(v, w))

print(x.dot(y))


(2,) (2,)
219
219
[[19 22]
 [43 50]]


In [45]:
z = np.eye(2)
print(x.dot(z))

[[1. 2.]
 [3. 4.]]


In [46]:
print(v @ w)

219


In [47]:

print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [48]:

print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [49]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))

10


In [50]:
print(x)
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2]
 [3 4]]
[4 6]
[3 7]


In [51]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v.shape)
print(v )
print("transpose\n", v.T)

###Broadcasting

In [52]:

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [53]:
vv = np.tile(v, (4, 1)) es of v on top of each othe
print(vv)

SyntaxError: ignored

In [54]:
y = x + vv
print(y)

NameError: ignored

In [55]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [56]:

print(np.reshape(v, (3, 1)) * w)

[[11 12]
 [ 0  0]
 [11 12]]


In [57]:

x = np.array([[1,2,3], [4,5,6]])

print(x + v)

[[2 2 4]
 [5 5 7]]


In [58]:


print((x.T + w).T)

[[12 13 14]
 [16 17 18]]


In [61]:

print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]
